name: "Action Metrics"
description: "Store metrics against your default branch and compare against your pull requests"
author: actionmetrics
branding:
  icon: bar-chart
  color: blue
inputs:
  default_branch:
    description: The default branch used by your repository
    required: false
    default: "main"
  github_token:
    description: GitHub token
    required: false
    default: ${{github.token}}
  repo:
    description: Repository name with owner (like actionmetrics/github-action)
    required: false
    default: ${{github.repository}}
  name:
    description: Artifact name (defaults to action-metrics.json)
    required: false
  path:
    description: Where to store the metrics
    required: false
    default: "./.action-metrics"
  fileName:
    description: Name of the file to store the metrics
    required: false
    default: "file.json"
  workflow:
    description: Workflow name
    required: true
  metricName:
    description: Metric name
    required: true
  metricValue:
    description: Metric value
    required: true
runs:
  using: node16
  main: "index.mjs"
