name: "Action Metrics"
description: "Store metrics against your default branch and compare against "
inputs:
  default-branch: # id of input
    description: "The default branch of the repository"
    required: true
    default: "main"
outputs:
  default:
    description: "Current metrics on the default branch"
    value: "{}"
  current:
    description: "Current metrics on the current branch"
    value: "{}"
  diff:
    description: "Difference in metrics between default branch and main branch"
    value: "{}"
runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        # Optional, GitHub token, a Personal Access Token with `public_repo` scope if needed
        # Required, if artifact is from a different repo
        # Required, if repo is private a Personal Access Token with `repo` scope is needed
        github_token: ${{secrets.GH_TOKEN}}
        # Required, workflow file name or ID
        workflow: action.yml
        workflow_conclusion: success
        branch: main
        # Optional, defaults to all types
        event: push
        name: version
    - name: Run Version
      shell: bash
      run: node index.mjs
